name: opinionated_bloc_generator
description: This generator aims to reduce boilerplate in an opinionated way. Opinionated Bloc Generator is the way we reduce this kind of bloc boilerplate in ours projects.

version: 0.2.1
homepage: https://github.com/rarolabs/opinionated_bloc

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  build: ^1.3.0
  source_gen: ^0.9.5
  analyzer: ^0.39.10
  _fe_analyzer_shared: ^4.0.0
  opinionated_bloc_annotations: ^0.0.1  
  freezed_annotation: ^0.7.1
  bloc: ^4.0.0

dev_dependencies:
  build_config: ^0.4.2
  build_runner: ^1.10.0
  freezed: ^0.10.9
  source_gen_test: ^0.1.1
  test: ^1.14.7
  